version: '3.2'
services:  
  shopizer:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ../../
        target: /data/shopizer
    container_name: shopizer-dev
    expose:
      - "8080"
      - "3306"
    network_mode: host

